name: issues details
on:
  issues:
    type: [opened, edited]
  workflow_dispatch:
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Get Issue title and body
        run: | 
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
      - name: Get all github context
        run: echo "${{ toJSON(github) }}"
    
